apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - name: application
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP